### ISSUE TITLE
BUG: inaccurate evaluation of 'day' corresponding with close price

### ISSUE THREAD

**Issue by maread99** [dpguthrie/yahooquery#127]
Thank you @dpguthrie for the great `yahooquery` library!!

The post-processing [market_prices](https://github.com/maread99/market_prices) library uses `yahooquery` by default to get price data. There I've employed a nasty hack or two to address a couple of bugs that would obviously be better fixed here at source.

The bug...

The following lines include the seemingly reasonable assumption that the day corresponding with a close price can be evaluated as the date part of the corresponding timestamp:
https://github.com/dpguthrie/yahooquery/blob/2e2be7225fa3f09260be620431a24480f41be1ff/yahooquery/utils/__init__.py#L129-L130

Whilst this holds for most cases, unfortunately it's not true for all...

```python
from yahooquery import Ticker
import pandas as pd
symbol = 'QAN.AX'  # Australian stock
ticker = Ticker(symbol)
start, end = pd.Timestamp('2022-11-10'), pd.Timestamp('2022-11-22')
interval = '1d'
adj_timezone = False
df = ticker.history(
    interval=interval, period=None, start=start, end=end, adj_timezone=adj_timezone
)
df
```
<table border="1" class="dataframe"><thead><tr style="text-align: right;"><th></th><th></th><th>high</th><th>open</th><th>close</th><th>volume</th><th>low</th><th>adjclose</th></tr><tr><th>symbol</th><th>date</th><th></th><th></th><th></th><th></th><th></th><th></th></tr></thead><tbody><tr><th rowspan="9" valign="top">QAN.AX</th><th>2022-11-09</th><td>6.030</td><td>5.98</td><td>5.98</td><td>5679481</td><td>5.950</td><td>5.98</td></tr><tr><th>2022-11-10</th><td>6.150</td><td>6.15</td><td>5.97</td><td>16357650</td><td>5.935</td><td>5.97</td></tr><tr><th>2022-11-13</th><td>5.940</td><td>5.94</td><td>5.82</td><td>8004783</td><td>5.775</td><td>5.82</td></tr><tr><th>2022-11-14</th><td>5.880</td><td>5.85</td><td>5.83</td><td>9281491</td><td>5.740</td><td>5.83</td></tr><tr><th>2022-11-15</th><td>5.870</td><td>5.84</td><td>5.80</td><td>7933161</td><td>5.770</td><td>5.80</td></tr><tr><th>2022-11-16</th><td>5.930</td><td>5.88</td><td>5.90</td><td>8911599</td><td>5.830</td><td>5.90</td></tr><tr><th>2022-11-17</th><td>5.935</td><td>5.90</td><td>5.88</td><td>6505128</td><td>5.870</td><td>5.88</td></tr><tr><th>2022-11-20</th><td>5.920</td><td>5.92</td><td>5.87</td><td>6309385</td><td>5.820</td><td>5.87</td></tr><tr><th>2022-11-21</th><td>5.920</td><td>5.92</td><td>5.87</td><td>6149307</td><td>5.820</td><td>5.87</td></tr></tbody></table>

The Australian exchange is open Mon-Fri. Nov 13 and Nov 20 are both Sundays although are included in the index, whilst Nov 11 and Nov 18 are both Friday although are missing. Also, the first indice is 2022-11-09 even though 'start' was passed as 2022-11-10. What's actually happened is that all the indices are defined as one day earlier than the data they represent (except the last one)...

If we take some code from under-the-bonnet we can replicate the dataframe before the offending lines at the top of this comment are executed...
```python
import yahooquery as yq
_convert_to_timestamp = yq.utils._convert_to_timestamp
start = _convert_to_timestamp(start)
end = _convert_to_timestamp(end, start=False)
params = {"period1": start, "period2": end}
params["interval"] = interval.lower()
data = ticker._get_data("chart", params)
df = pd.DataFrame(data[symbol]["indicators"]["quote"][0])
if data[symbol]["indicators"].get("adjclose"):
    df["adjclose"] = data[symbol]["indicators"]["adjclose"][0]["adjclose"]
df.index = pd.to_datetime(data[symbol]["timestamp"], unit="s") + pd.Timedelta(
    (data[symbol]["meta"]["gmtoffset"] * adj_timezone), "s"
)
df
```
<table border="1" class="dataframe"><thead><tr style="text-align: right;"><th></th><th>high</th><th>open</th><th>close</th><th>volume</th><th>low</th><th>adjclose</th></tr></thead><tbody><tr><th>2022-11-09 23:00:00</th><td>6.030</td><td>5.98</td><td>5.98</td><td>5679481</td><td>5.950</td><td>5.98</td></tr><tr><th>2022-11-10 23:00:00</th><td>6.150</td><td>6.15</td><td>5.97</td><td>16357650</td><td>5.935</td><td>5.97</td></tr><tr><th>2022-11-13 23:00:00</th><td>5.940</td><td>5.94</td><td>5.82</td><td>8004783</td><td>5.775</td><td>5.82</td></tr><tr><th>2022-11-14 23:00:00</th><td>5.880</td><td>5.85</td><td>5.83</td><td>9281491</td><td>5.740</td><td>5.83</td></tr><tr><th>2022-11-15 23:00:00</th><td>5.870</td><td>5.84</td><td>5.80</td><td>7933161</td><td>5.770</td><td>5.80</td></tr><tr><th>2022-11-16 23:00:00</th><td>5.930</td><td>5.88</td><td>5.90</td><td>8911599</td><td>5.830</td><td>5.90</td></tr><tr><th>2022-11-17 23:00:00</th><td>5.935</td><td>5.90</td><td>5.88</td><td>6505128</td><td>5.870</td><td>5.88</td></tr><tr><th>2022-11-20 23:00:00</th><td>5.920</td><td>5.92</td><td>5.87</td><td>6309385</td><td>5.820</td><td>5.87</td></tr><tr><th>2022-11-21 05:10:23</th><td>5.920</td><td>5.92</td><td>5.87</td><td>6149307</td><td>5.820</td><td>5.87</td></tr></tbody></table>

We see that the Yahoo API uses the session's UTC open time to index daily data. In the case of Sydney this is an hour before UTC midnight. This is why the offending line wrongly assumes the 'day' corresponding with the data is the day immediately before the day that the prices actually relate to.

Also, worth pointing out that as this example was produced after the close on Nov 21 it shows the 'duplicate indice' issue as raised in #123 and fixed in #124 (here the last two indices represent the same day's data, the only difference being the volume). The duplicate is actually a specific case of the issue highlighted by #36. Basically, the Yahoo API represents any interval which has yet to close (call it the **'live interval'**) with the current timestamp and current price. For daily data this is why we get today's 'close' before the close - it's just the price at the time of the call. However, with daily data this 'live-indice' continues to be included in the return even after the data for the day has been added. The 'live-indice' is timestamped above as the auction close (just after 05:10 UTC). It represents the same period of data as the row above (the actual close data). This stuck 'live indice' is what the #124 fix intended to remove. However here, because of the different date components, it won't register as a duplicate and hence won't be removed, regardless of the fix.

Passing "adj_timezone" as True in the above example would resolve the issue in this case as the timezone adjustment is applied before the date component assumption is made. However, the issue also applies beyond stocks sitting towards the edge of the date line. It effects currencies too, at least for six months of each year...
```python
ticker = Ticker('GBPUSD=X')
start, end = pd.Timestamp('2022-03-14'), pd.Timestamp('2022-04-05')
df = ticker.history(
    interval=interval, period=None, start=start, end=end, adj_timezone=True
)
weekday = pd.DatetimeIndex(df.index.droplevel(0)).weekday
df["weekday"] = weekday
df
```
<table border="1" class="dataframe"><thead><tr style="text-align: right;"><th></th><th></th><th>volume</th><th>high</th><th>low</th><th>open</th><th>close</th><th>adjclose</th><th>weekday</th></tr><tr><th>symbol</th><th>date</th><th></th><th></th><th></th><th></th><th></th><th></th><th></th></tr></thead><tbody><tr><th rowspan="17" valign="top">GBPUSD=X</th><th>2022-03-14</th><td>0</td><td>1.307873</td><td>1.301050</td><td>1.304955</td><td>1.305030</td><td>1.305030</td><td>0</td></tr><tr><th>2022-03-15</th><td>0</td><td>1.308866</td><td>1.300136</td><td>1.301084</td><td>1.301185</td><td>1.301185</td><td>1</td></tr><tr><th>2022-03-16</th><td>0</td><td>1.311441</td><td>1.303662</td><td>1.304500</td><td>1.304649</td><td>1.304649</td><td>2</td></tr><tr><th>2022-03-17</th><td>0</td><td>1.321109</td><td>1.308952</td><td>1.314078</td><td>1.314112</td><td>1.314112</td><td>3</td></tr><tr><th>2022-03-18</th><td>0</td><td>1.318166</td><td>1.311200</td><td>1.316049</td><td>1.316041</td><td>1.316041</td><td>4</td></tr><tr><th>2022-03-21</th><td>0</td><td>1.320987</td><td>1.312836</td><td>1.316067</td><td>1.316084</td><td>1.316084</td><td>0</td></tr><tr><th>2022-03-22</th><td>0</td><td>1.327246</td><td>1.312095</td><td>1.316794</td><td>1.316829</td><td>1.316829</td><td>1</td></tr><tr><th>2022-03-23</th><td>0</td><td>1.329893</td><td>1.317627</td><td>1.326964</td><td>1.326647</td><td>1.326647</td><td>2</td></tr><tr><th>2022-03-24</th><td>0</td><td>1.321475</td><td>1.315789</td><td>1.320655</td><td>1.320603</td><td>1.320603</td><td>3</td></tr><tr><th>2022-03-25</th><td>0</td><td>1.322559</td><td>1.316170</td><td>1.319592</td><td>1.319575</td><td>1.319575</td><td>4</td></tr><tr><th>2022-03-27</th><td>0</td><td>1.317888</td><td>1.306865</td><td>1.317697</td><td>1.317627</td><td>1.317627</td><td>6</td></tr><tr><th>2022-03-28</th><td>0</td><td>1.315928</td><td>1.305227</td><td>1.309998</td><td>1.310358</td><td>1.310358</td><td>0</td></tr><tr><th>2022-03-29</th><td>0</td><td>1.318061</td><td>1.309158</td><td>1.309295</td><td>1.309380</td><td>1.309380</td><td>1</td></tr><tr><th>2022-03-30</th><td>0</td><td>1.317089</td><td>1.310960</td><td>1.313681</td><td>1.313888</td><td>1.313888</td><td>2</td></tr><tr><th>2022-03-31</th><td>0</td><td>1.314613</td><td>1.308866</td><td>1.314579</td><td>1.314700</td><td>1.314700</td><td>3</td></tr><tr><th>2022-04-03</th><td>0</td><td>1.313629</td><td>1.309518</td><td>1.310513</td><td>1.310376</td><td>1.310376</td><td>6</td></tr><tr><th>2022-04-04</th><td>0</td><td>1.316690</td><td>1.310049</td><td>1.311303</td><td>1.311458</td><td>1.311458</td><td>0</td></tr></tbody></table>

Notice that up to Mar 25 the days are Mon-Fri, as required, although thereafter they change to Sun-Thu. This happens regardless that "adj_timezone" was passed here as True. The reason behind this one is the change to Daylight Saving Time in the UK.

There are also issues with 24 hour futures that I won't go into here.

So, what to do? It's not possible to map the timestamps to days with absolute confidence without knowledge of the underlying exchanges and every opening time of those exchanges! I suspect this is why Yahoo doesn't even try. In the end it becomes a somewhat arbitrary exercise (do you associate a 24 hour instrument that opens at 17:00 with the day it opens on or the day after?). **What I've found works well, in so much as meeting likely expectations, is to say that when the open timestamp, in the local timezone, is before 12:00 midday then the corresponding day should be the date of the timestamp, whilst if after midday it should be assigned the date of the following day**. (EDIT: in the PR I'm going to make the cut-off 14:00 local time - I recall Hong Kong can have opens as late as 13:00 when the exchange cancels the morning session due to adverse weather.)

I'll offer a PR that implements this, just wanted to raise the issue here to offer background.

(On a related point, the 'gmtoffset' can't appreciate changes to DST and so shouldn't be used to evaluate the local time - I'll raise under a separate issue.)

**Comment by dpguthrie** [comment]
Appreciate the writeup here @maread99!  I'd absolutely welcome a PR that solves this issue.

**Comment by maread99** [comment]
No worries, I appreciate you having written the library! I'll offer up a PR tomorrow.

@dpguthrie, a bit of an aside, I noticed you closed some issues last month noting that user suggestions weren't planned or were outside the intended scope of `yahooquery`. You might be interested in having a quick look at [market_prices](https://github.com/maread99/market_prices). It's pretty much a more functional interface that sits on top of `ticker.history`. At least a couple of the closed issues are covered there. Might be a useful reference to offer users who are after enhanced querying / more post-processing of price data.

Cheers
Marcus

**Comment by maread99** [comment]
### A note on the **'live indice'**
This is a note on how I'm proposing to handle the 'live indice' for daily data in the PR #129 (thought I'd include it here to keep all the background together).

In the initial comment I mentioned how the last indice of any daily data that includes 'today' is returned by Yahoo as a 'live indice' that's timestamped as the most recent trade.

I don't believe it's possible to evaluate a 'day' for this timestamp without knowledge of the underlying exchange's opening and closing times. As noted earlier, mapping even a localised datetime to a day isn't as simple as taking the date component. Whilst datetimes representing _session opens_ can be reasonably mapped to days on the basis noted in bold (towards end of initial comment), the same isn't true for the 'live indice' datetime which could, in some cases, fall anywhere in the 24 hours following the session open.

So, I've proposed leaving any 'live indice' in the index as a `datetime.datetime` that fully reflects both the date and time components. This would allow users to easily identify the row as a 'live indice' (removing the ambiguity raised in #36) and handle it as they require. The 'live indice' is removed in the event that the close price for the session has already been posted (evaluated by way of checking if the difference between any live indice and the prior indice, i.e. the prior session open, is less that 24 hours). This avoids the duplicate issue also mentioned in the initial comment.

Worth noting, [market_prices](https://github.com/maread99/market_prices) does map the `live indice` to a day (session) for daily data, although it can only do this because:
* it maps every symbol to an exchange.
* it uses [exchange_calendars](https://github.com/gerrymanoim/exchange_calendars) to get knowledge of every minute that every exchange is open on and which session each of those minutes maps to.

**NOTE** The PR #129 could be considered to include a breaking change, although I don't think it's any more significant than the changes recently introduced by #118 which would also be included in the next release.

**Comment by maread99** [comment]
Fixed by #129

**Comment by gerardsyd** [comment]
Hi - I'm getting what seems to be a related problem. 

If I try this:
```
import yahooquery as yq

ticker = yq.Ticker('BHP.AX')
df = ticker.history(interval='1d', start=datetime(2023, 3, 17),
                    end=datetime(2023, 3, 20))
```

I get:
```
                   open  high   low  close    volume  adjclose
symbol date                                                   
BHP.AX 2023-03-17 43.25 43.69 43.13  43.39  23112109     43.39
```

The issue is, there is data for the stock on 20 March 2023. Changing adj_timezone = False does not solve the problem. 

If I increment the end date by one day, this seems to work but then the last days' data does not show:

```
import yahooquery as yq

ticker = yq.Ticker('BHP.AX')
df = ticker.history(interval='1d', start=datetime(2023, 3, 17),
                    end=datetime(2023, 3, 21))
```

```
                   open  high   low  close    volume  adjclose
symbol date                                                   
BHP.AX 2023-03-17 43.25 43.69 43.13  43.39  23112109     43.39
       2023-03-20 43.35 43.85 42.89  42.96   6916826     42.96
```

Any ideas what is causing this behaviour? I can of course just increment by one day to get the accurate date but just wondering what is happening. 

Thanks!

**Comment by maread99** [comment]
Hi @gerardsyd

I can't reproduce the output from your first example, rather I get returned the two days of data that would be expected.

Can you confirm which version of `yahooquery` you're using...

```python
import yahooquery as yq
print(yq.__version__)
```

The latest version if 2.3.1

**Comment by gerardsyd** [comment]
Hi @maread99 thanks for that. It was indeed a version issue. I was using 2.3.0. 
Rookie error! Thanks for the response - all working now!
