### ISSUE TITLE
When pulling crypto data on the weekends it does not pull the previous day for some odd reason... 

### ISSUE THREAD

**Issue by nehctuk** [dpguthrie/yahooquery#136]
<img width="669" alt="Screen Shot 2023-01-21 at 12 04 27 PM" src="https://user-images.githubusercontent.com/19308156/213878317-a6d6c9c9-cd14-4c77-9da1-6cd8d640f24e.png">

I have noticed this now two weekends in a row, when pulling crypto data over the weekend it drops the previous day or two data.

**Comment by dpguthrie** [comment]
I wasn't able to replicate today.  This is most likely fixed with the new release 2.3.0.  I'm going to close this for now but please feel free to open if you run into this again.

**Comment by nehctuk** [comment]
I am still seeing this issue in 2.3.1 when pulling HBAR-USD or other crypto currencies over the weekend. Interestingly enough the final day is also a datetime now when everything else is a date. It also does not happen for normal stocks, only crypto related tickers. Not sure why but if I can do anything to help here please let me know. 

<img width="776" alt="Screen Shot 2023-04-01 at 7 30 01 PM" src="https://user-images.githubusercontent.com/19308156/229322747-9271044a-463c-4434-b9ab-9f94a81af035.png">

**Comment by nehctuk** [comment]
When I go back to version 2.2.15 I do not have the datetime issue: 

<img width="761" alt="Screen Shot 2023-04-01 at 7 36 45 PM" src="https://user-images.githubusercontent.com/19308156/229322842-e58914bf-7857-4464-87aa-4377fe2c252c.png">

**Comment by nehctuk** [comment]
It might also be a Saturday issue and not a weekend issue, I will confirm tomorrow with version 2.2.15 and 2.3.1.

**Comment by nehctuk** [comment]
So outside of the datetime issue with version 2.3.1, yahoo itself is missing the data so I don't think this is fixable.

**Comment by nehctuk** [comment]
So it does seem to only happen on Saturday for yahoo's data, so strange.

**Comment by maread99** [comment]
Hi @nehctuk

The `datetime` type for the last indice is the intended behaviour, as described by the 'Returns' section of the method doc. Also, see [here](https://github.com/dpguthrie/yahooquery/issues/169#issuecomment-1481914207).
